name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '20[0-9][0-9].3.*'
      - '20[0-9][0-9].6.*'
      - '20[0-9][0-9].9.*'
      - '20[0-9][0-9].12.*'
  pull_request:
    branches:
      - '**'


jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Test Docker Image
        run: docker build -t test-image --target run-stage .

      - name: Lint Code in Container
        run: docker run test-image yarn lint

      - name: Test Code in Container
        run: docker run test-image yarn test:unit

      - name: Docker Logout
        run: docker logout


  tar:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/test'
    env:
      APP_NAME: corteza-webapp-one
    needs:
      - test
    steps:

      - name: Set ENV Variables
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/(.*)$ ]] || [[ $GITHUB_REF =~ ^refs/heads/(.*)$ ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            exit 1
          fi

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t build-image --target build-stage .

      - name: Copy Dist Folder
        run: docker cp $(docker create build-image):/app/dist .

      - name: Compress tar.gz
        run: mkdir files; tar -C dist -czf files/${{ env.APP_NAME }}-${{ env.VERSION }}.tar.gz $(dir dist)

      - name: Upload tar.gz
        run: |
          docker run --rm \
                     --env REMOTE_SERVER="sftp://frs.sourceforge.net" \
                     --env USERNAME="${{ secrets.SOURCEFORGE_USERNAME }}" \
                     --env PASSWORD="${{ secrets.SOURCEFORGE_PASSWORD }}" \
                     --env REMOTE_PATH="/home/frs/project/cortezaproject/${{ env.APP_NAME }}" \
                     --env DEBUG=true \
                     --env DELETE_FILES=true \
                     --volume "$(pwd)/files":/files \
                     cortezaproject/lftp:latest /upload

      - name: Docker Logout
        run: docker logout


  docker:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/test'
    env:
      IMAGE: cortezaproject/corteza-webapp-one
    needs:
      - test
    steps:

      - name: Set ENV Variables
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/(.*)$ ]] || [[ $GITHUB_REF =~ ^refs/heads/(.*)$ ]]; then
            echo "TAG=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            exit 1
          fi

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE }}:${{ env.TAG }} .

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Docker Logout
        run: docker logout
